spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ranking
    username: ranking
    password: ranking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
